Add Joint Travel Regulations?
willswire/pubs pull request #1
Opened 2021-08-13 19:52 UTC by DrewStephensCoding

Wanted to see if it would be possible to add the JTR as a subset to the pubs, the same way you did the AFROTC and Honor Guard pubs.  The JTR has been one of the most frequently requested publications, even though it's not strictly an AFI or Air Force pub.  I think it still has a good benefit being in the app....thoughts?

2021-08-15 16:39 UTC, willswire requested changes
Please see the comment for `data.txt`

2021-08-15 16:39 UTC, willswire commented on data.txt
> +[{"PubID":0,
Hey @DrewStephensCoding! Thanks for the PR. Please reformat `data.txt` so that it is a single line of JSON formatted code.

2021-08-15 17:15 UTC, DrewStephensCoding commented on data.txt
> +[{"PubID":0,
Ah shoot, I used a site to prettify the json so I can read it 😂 had a hunch that might cause a problem! I'll fix it ASAP

2021-08-15 23:03 UTC, DrewStephensCoding commented
@willswire I think I corrected it?

2021-08-16 00:13 UTC, willswire commented
Looks good!

2021-08-16 00:13 UTC, merged